var tablerow_json = [
  {
    First_Name: "HITEN",
    Middle_Name: "-",
    Last_Name: "GUPTA",
    Email: "123@sourcefuse.com",
    Phone_Number: 9156524334,
    Role: "JE",
    Address: "PUNJAB",
    Edit_Delete: "button",
  },
  {
    First_Name: "HITEN",
    Middle_Name: "1",
    Last_Name: "GUPTA",
    Email: "12311@sourcefuse.com",
    Phone_Number: 9156524334,
    Role: "JE",
    Address: "PUNJAB",
    Edit_Delete: "button",
  },

  {
    First_Name: "HITEN",
    Middle_Name: "2",
    Last_Name: "GUPTA",
    Phone_Number: 9156522334,
    Role: "JE",
    Address: "PUNJAB",
    Email: "1231@sourcefuse.com",
    Edit_Delete: "button",
  },

  {
    Last_Name: "GUPTA",
    Middle_Name: "3",
    First_Name: "HITEN",
    Email: "1235@sourcefuse.com",
    Phone_Number: 9154524334,
    Role: "JE",
    Address: "PUNJAB",
    Edit_Delete: "button",
  },

  {
    First_Name: "HITEN",
    Middle_Name: "4",
    Last_Name: "GUPTA",
    Email: "127@sourcefuse.com",
    Phone_Number: 9156624334,
    Role: "JE",
    Address: "PUNJAB",
    Edit_Delete: "button",
  },

  {
    First_Name: "HITEN",
    Middle_Name: "5",
    Last_Name: "GUPTA",
    Email: "1239@sourcefuse.com",
    Phone_Number: 9156555334,
    Role: "JE",
    Address: "PUNJAB",
    Edit_Delete: "button",
  },
];
